"""update_document_model_fields

Revision ID: a33119df602d
Revises: 05b9aed46a26
Create Date: 2025-12-19 23:10:28.643546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a33119df602d'
down_revision: Union[str, Sequence[str], None] = '05b9aed46a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('academic_year', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('body', sa.Text(), nullable=False))
    op.drop_column('documents', 'extra_metadata')
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('documents', 'body')
    op.drop_column('documents', 'academic_year')
    op.drop_column('documents', 'type')
    # ### end Alembic commands ###
